version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: scheduler-app
    container_name: go-fiber-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - .env
